---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: content/_index.md
  label: Home
- type: document
  path: content/about.md
  label: About
- type: heading
  label: Products
- type: directory
  path: content/products/skin-care
  label: Skin Care
  create: all
  match: "**/*"
- type: directory
  path: content/products/coloring-hair-shampoo
  label: Coloring Hair Shampoo
  create: all
  match: "**/*"
- type: directory
  path: content/products/hair-regrowth
  label: Hair Regrowth
  create: all
  match: "**/*"
- type: directory
  path: content/products/dusty-forest-herb-extract-hair
  label: Dusty Forest Herb Extract Hair
  create: all
  match: "**/*"
- type: directory
  path: content/products/natural-hair-color-cream
  label: Natural Hair Color Cream
  create: all
  match: "**/*"
- type: directory
  path: content/products/hair-repair
  label: Hair Repair
  create: all
  match: "**/*"
- type: directory
  path: content/products/hand-sanitizer-spray
  label: Hand Sanitizer Spray
  create: all
  match: "**/*"
- type: directory
  path: content/products/pet-shampoo
  label: Pet Shampoo
  create: all
  match: "**/*"
- type: directory
  path: content/products/pet-mask
  label: Pet Mask
  create: all
  match: "**/*"
- type: directory
  path: content/products/other-pet-care
  label: Other Pet Care
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.76.5
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.76.5
