---
label: Product Template
hide_body: false
fields:
- name: title
  type: text
  config:
    required: true
    min: 1
  description: Enter a title for the product
  label: Product Title
- name: item_number
  type: text
  config:
    required: true
    min: 1
  label: Item Number
  description: Enter the product item number
- name: product_description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Product Description
  description: Enter a description for the product
