---
label: Product Template
hide_body: false
fields:
- name: title
  type: text
  config:
    required: true
    min: 1
  description: Enter a title for the product
  label: Product Title
- name: itemno
  type: text
  config:
    required: false
    min: 0
  label: Item Number
  description: Enter the product item number
- name: images
  type: image_gallery
  config: {}
  label: Product Images
  description: Upload product images
- name: products
  type: select
  default: ''
  config:
    required: true
    options:
    - Skin Care
    - Coloring Hair Shampoo
    - Hair Regrowth
    - Dusty Forest Herb Extract Hair
    - Natural Hair Color Cream
    - Hair Repair
    - Hand Sanitizer Spray
    - Pet Shampoo
    - Pet Mask
    - Other Pet Care
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Product Category
  description: Select the product category
pages:
- content/products/pet-shampoo/never-greasy-stinky-dog-shampoo.md
- content/products/skin-care/anti-aging-24k-gold-collagen-hydrogel-facial-mask.md
- content/products/skin-care/bamboo-charcoal-collagen-mask.md
